### ISSUE TITLE
Removing methods that rely on void*'s from the parent array class.

### ISSUE THREAD

**Issue by NickSimmons97** [jonvolfson/cs4500-api#14]
In line with one of the previous issues regarding the get method in the parent array class, the following methods-- virtual void append(void* to_add), virtual void insert(void* to_add, size_t index), virtual void append(void* to_add), should also only be implemented in the children class. Casting the to_add argument's to their desired types from a void* is not guaranteed. Void* will change based on the machine that the code it is running on. Jan Vitek was also the source of this information. Please let us know if you can update this, thank you for your time.

**Comment by jonvolfson** [comment]
resolved
